# Example configuration for the 'epibench interpret' command
# This file provides a template for configuring model interpretation.

# Path to the configuration file used during model training.
# Required to reconstruct the model architecture.
training_config: config/train_config.example.yaml

# Interpretation Settings
interpretation:
  # Method to use (e.g., IntegratedGradients).
  method: IntegratedGradients
  # Batch size for interpretation passes.
  internal_batch_size: 64

  # Parameters specific to Integrated Gradients.
  integrated_gradients:
    # Number of steps for the approximation integral.
    n_steps: 50 # Default: 50
    
    # Baseline for comparison ('zero', 'random', path/to/custom_baseline.h5).
    # Can be commented out to use default ('zero').
    baseline_type: "zero" 
    
    # Index of the target output neuron to attribute for (usually 0 for single-output models).
    target_output_index: 0 # Default: 0

# Feature Extraction Settings (Optional)
# Define how to extract features from attribution scores.
# Alternatively, use `feature_extraction: {}` to rely on defaults.
feature_extraction:
  # Use absolute attribution values before ranking/thresholding.
  use_absolute_value: true # Default: true
  
  # Option 1: Extract top K features (overrides threshold if both specified).
  # top_k: 100 # Default: None
  
  # Option 2: Extract features with attribution score above a threshold.
  threshold: 0.1 # Default: None

# Output Settings
output:
  # Whether to save raw attribution scores (HDF5 or .npy).
  save_attributions: true # Default: true
  
  # Whether to generate and save visualization plots.
  generate_plots: true # Default: true
  
  # Prefix for output filenames (saved in CLI --output-dir).
  filename_prefix: "example_interpretation" # Default: "interpretation"

# Visualization Settings (Required if output.generate_plots is true)
visualization:
  # List of histone mark names (order determines plot order).
  histone_names: 
    - H3K4me
    - H3K4me3
    - H3K36me3
    - H3K27me3
    - H3K27ac
    - H3K9me3
  
  # Paths to ground truth BigWig files corresponding to histone_names.
  # REQUIRED if generate_plots is true. Use relative paths if possible.
  histone_bigwig_paths:
    - path/to/data/H3K4me.bw
    - path/to/data/H3K4me3.bw
    - path/to/data/H3K36me3.bw
    - path/to/data/H3K27me3.bw
    - path/to/data/H3K27ac.bw
    - path/to/data/H3K9me3.bw

  # Resolution (dots per inch) for saved plot images.
  plot_dpi: 150 # Default: 150

  # Max number of individual sample plots to generate (0 or null to disable).
  max_samples_to_plot: 100 # Default: 20

# Logging Settings
logging:
  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL).
  level: INFO # Default: INFO
  # Optional: Path to save log file (relative to output dir).
  # file: interpretation_log.log 