# Example Samples Configuration for EpiBench Orchestration
# Defines multiple sample runs for scripts like run_full_pipeline.py.
# 
# --- How to Use This File --- #
# 1. Copy this file (e.g., to `my_runs.yaml`).
# 2. Edit your copy to define the pipeline runs you want to execute.
# 3. Each item in the list (starting with `- name: ...`) defines one full pipeline run.
# 4. For each run, specify:
#    - `name`: A unique identifier for the run.
#    - `process_data_config`: Path to the config for the data processing step.
#    - `train_config`: Path to the config for the model training step.
#    - Optional overrides (e.g., `input_data_for_prediction`, output names).
# 5. Run the orchestration script, passing your config file:
#    `python scripts/run_full_pipeline.py --samples-config config/my_runs.yaml`
# The script will iterate through each sample defined below, executing the pipeline 
# with the specified configurations for each.
# Relative paths are typically resolved from the project root.
# --------------------------- #

# List of sample configurations to run.

# Example 1: Basic run using standard example configs.
- name: AML_Sample_Run_01
  # REQUIRED: Path to the process-data config for this sample.
  process_data_config: config/process_config.example.yaml
  # REQUIRED: Path to the train config for this sample.
  train_config: config/train_config.example.yaml
  # OPTIONAL: Input data for prediction step (defaults to 'test' split from process-data).
  # input_data_for_prediction: path/to/aml_external_validation.h5

# Example 2: Run using configs specific to a different cell type (CD34).
# Also demonstrates overriding default output names.
- name: CD34_Sample_Run_01
  # REQUIRED: Process config specific to CD34.
  process_data_config: config/process_config_cd34.example.yaml # Assumes this example exists
  # REQUIRED: Training config specific to CD34.
  train_config: config/train_config_cd34.example.yaml # Assumes this example exists
  # OPTIONAL: Override default output names/paths for this sample.
  training_output_name: training_cd34_example
  checkpoint_filename: cd34_example_best.pth
  # evaluation_output_name: eval_cd34_example # Another optional override example
  # prediction_output_name: predict_cd34_example # Another optional override example

# Example 3: Reusing a process config but using a different model/training config.
- name: AML_Sample_Run_02_Different_Model
  # REQUIRED: Reuse process config from AML_Sample_Run_01.
  process_data_config: config/process_config.example.yaml
  # REQUIRED: Use a different training config for this sample.
  train_config: config/train_config_v2.example.yaml # Assumes this example exists
  # OPTIONAL: Overrides for evaluation and prediction outputs.
  evaluation_output_name: eval_aml_v2_example
  prediction_output_name: predict_aml_v2_example

# Add more sample configurations as needed. 