# Training configuration
model:
  type: SimpleCNN # Example model type
  params:
    num_classes: 1 # Example model parameter

optimizer:
  type: Adam
  params:
    lr: 0.001
    weight_decay: 0.0001

training:
  epochs: 50
  batch_size: 64
  patience: 5 # For early stopping
  checkpoint_dir: 'checkpoints/simple_cnn' # Directory to save model checkpoints

data:
  train_hdf5_path: 'data/processed/train_sequences.hdf5'
  val_hdf5_path: 'data/processed/val_sequences.hdf5'
  # Add any relevant dataset parameters here
  # e.g., include_chromosomes: ['chr1', 'chr2']
  # e.g., exclude_chromosomes: ['chrM']

# Add other relevant sections like loss function, etc.
loss:
  type: BCEWithLogitsLoss
